services:
  - type: web
    name: messageboard
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
